### PR TITLE
fix deprecation warnings in Elixir 1.9.0

### PR DESCRIPTION
**Pull request by woylie**

### CODE REVIEW

**Comment by woylie** [comment]
Can someone merge and release this, please? This is basically preventing us from upgrading our projects to Elixir 1.9.0, because a ton of warnings are emitted when running our tests.

**Comment by hylkealons** [comment]
yes please merge! Same issue as @woylie: can't upgrade to 1.9.0 because of this issue.

Thanks for the PR!

**Comment by fartek** [comment]
guys can we get this merged soon please? 🙏 👍

**Comment by dabeat** [comment]
It'd be very helpful if you could please get this PR merged!

**Comment by hylkealons** [comment]
@jonasschmidt any update on this?

**Comment by jonasschmidt** [comment]
Sorry for the long delay. I was on sabbatical and had my GitHub email still set to the company address, so I never got the notifications for the open issues. The PR has been merged and released in version `0.6.2`. Thank you for taking care of this 🙇

**Comment by woylie** [comment]
Thanks for merging!

**Pull request merged**
