### PR TITLE
Implement the custom format validator

### PR DESCRIPTION
**Pull request by arjan**
See #50

### CODE REVIEW

**Comment by jonasschmidt** [comment]
Sounds like a great idea! I will have a look at the PR later today and give some feedback.

**Comment by arjan** [comment]
The potential issue I see with this solution that it's using the Application environment. Meaning that when two independent parts of the project use a custom format validator, they need to ensure that they reach agreement of the callback module to use.

A better solution would be to add an extra `context` argument to the validate call, which can carry this validator configuration all the way into the validation. This would also allow to put custom values in the context which then could be used in the validation callback. However, this would be a very large change, wiring that context argument through every function call.. so my proposal is maybe not ideal, but quite pragmatic.

**Comment by arjan** [comment]
I force-pushed to remove my last commit which made the return value "nicer", so now the validator should return a list of errors again.

I agree that passing down a format validator inside the struct would be nice, but it's additional to this PR, I'll create a ticket for it after this is merged.

**Comment by jonasschmidt** [comment]
Ah, sorry, that was a misunderstanding. I prefer the version you had in the end, where the format validator function just returns a boolean. I should have phrased that comment a bit more clearly.

Any comments on the idea of putting the custom format validator in the schema struct?

**Comment by arjan** [comment]
Oh, hah, oops :-) Git reflog ftw, I've pushed again.

About the custom format validator, I think it could be stored in the `%Root{}` struct under an `options` key or whatever. And then pass this options down into the `ExJsonSchema.Validator.validate_aspect` function, which forwards it to each validator.

**Comment by arjan** [comment]
But like I said maybe it's better to do that in a separate PR.

**Comment by jonasschmidt** [comment]
Ok, that makes sense. I will merge and release the current state. Thank you for the excellent work 👍

**Comment by arjan** [comment]
Thanks!

**Comment by jonasschmidt** [comment]
Just released on Hex as well as version `0.7.0`.

**Pull request merged**
